[package]
name = "fftviz"
version = "0.1.1"
edition = "2021"
authors = ["Gursimar Singh <gursi26.dev@gmail.com>"]
license = "MIT"
description = "A quick FFT visualizer for audio files"
readme = "README.md"
homepage = "https://github.com/gursi26/fftviz"
repository = "https://github.com/gursi26/fftviz"
keywords = ["cli"]
categories = ["command-line-utilities"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.0", features = ["derive"] }
raylib = "3.7.0"
rayon = "1.9.0"
rodio = "0.17.3"
serde = { version = "1.0.197", features = ["derive"] }
spectrum-analyzer = "1.5.0"
